version : "3.3"
services :
  web :
     build : .
     ports :
         - "8000:8000"
     volumes:
      - ./volume/store_data/db.sqlite3:/data/db.sqlite3
    web :
     build : .
     ports :
         - "8001:8000"
     volumes:
      - ./volume/store_data/db.sqlite3:/data/db.sqlite3
